### ISSUE TITLE
Restart of foreman-proxy fails after hdm proxy installation

### ISSUE THREAD

**Issue by tuxmea** [betadots/smart_proxy_hdm#13]
Logfile shows error:

```
2024-01-23T13:12:43  [E] Disabling all modules in the group ['hdm'] due to a failure in one of them:
 (<unknown>): did not find expected key while parsing a block mapping at line 3 column 1
2024-01-23T13:12:43  [W] Error details for Disabling all modules in the group ['hdm'] due to a failu
re in one of them: (<unknown>): did not find expected key while parsing a block mapping at line 3 co
lumn 1: <Psych::SyntaxError>: (<unknown>): did not find expected key while parsing a block mapping a
t line 3 column 1
/usr/share/ruby/psych.rb:456:in `parse'
/usr/share/ruby/psych.rb:456:in `parse_stream'
/usr/share/ruby/psych.rb:390:in `parse'
/usr/share/ruby/psych.rb:277:in `load'
/usr/share/foreman-proxy/lib/proxy/settings.rb:27:in `read_settings_file'
/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:300:in `load_configuration_file'
/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:271:in `load_settings'
/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:263:in `load_plugin_settings'
/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:80:in `load_plugin_settings'
/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:167:in `each'
/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:167:in `initialize_plugins'
/usr/share/foreman-proxy/lib/launcher.rb:177:in `launch'
/usr/share/foreman-proxy/bin/smart-proxy:6:in `<main>'
```

**Comment by oneiros** [comment]
Have you tried with

```yaml
:enabled: true
```

or only with

```yaml
:enabled: https
```

as shown in #12?

**Comment by tuxmea** [comment]
same error using `:enabled: true`

**Comment by oneiros** [comment]
Looks like you may have a superfluous comma at the end of this line here:

```yaml
:hdm_user: 'api@domain.tld',
```

**Comment by tuxmea** [comment]
Sorry. Fixed. Thank you.
